package com.volume.transfers;

public enum TransferStatus {
    CREATED,
    REQUESTING_AUTHORIZATION_URL,
    AUTHORIZATION_URL_REQUEST_SUCCEEDED,
    AUTHORIZATION_URL_REQUEST_FAILED,
    USER_REDIRECTED_TO_AUTHORIZATION_URL,
    AUTHORIZATION_SUCCEEDED,
    AUTHORIZATION_FAILED,
    STARTING_PAYMENT,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED
}
