package com.volume.yapily

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue
import yapily.sdk.AccountIdentification
import java.util.*

interface YapilyAccountIdentification {
    fun toYapily(): AccountIdentification
    fun toDbString(): String
}

data class YapilyInstitutionId(val value: String) {
    init {
        // validate here
    }

    companion object {
        val MODELO_SANDBOX = "modelo-sandbox"
        fun modeloSandbox() : YapilyInstitutionId {
            return YapilyInstitutionId(MODELO_SANDBOX)
        }
    }
}


/**
 * TODO: find and describe how it works. This is a very important for us identifier.
 */
data class YapilyPaymentIdempotencyId(val value: String) {
    init {
        // validate here
    }

    companion object {
        fun random(): YapilyPaymentIdempotencyId {
            return YapilyPaymentIdempotencyId(UUID.randomUUID().toString().replace("-", ""))
        }
    }
}

/**
 * Assigned by Yapily when user is created using POST /users (https://docs.yapily.com/api/#create-user)
 */
data class YapilyUserId(val value: UUID) : java.io.Serializable {
    init {
        // validate here
    }
    companion object {
        fun random() : YapilyUserId {
            return YapilyUserId(UUID.randomUUID())
        }
        @JsonCreator
        fun fromString(value: String): YapilyUserId = YapilyUserId(UUID.fromString(value))
    }

    @JsonValue
    fun asString(): String = value.toString()
}

/**
 * From Yapily docs:
 *  here: https://docs.yapily.com/api/#tocS_NewApplicationUser
 *  description:
 *      Additional unique identifier that you can specify when creating a new User to more easily reference it.
 *
 *  It is either created by us and passed to POST /user or, if not provided, will be generated by Yapily.
 *  Yapily docs: https://docs.yapily.com/api/#create-user
 */
data class YapilyApplicationUserId(val value: String) : java.io.Serializable {
    init {
        // validate here
    }
    companion object {
        fun random() : YapilyApplicationUserId {
            return YapilyApplicationUserId(UUID.randomUUID().toString().replace("-", ""))
        }
    }

    @JsonValue
    fun asString(): String = value
}

data class YapilyReferenceUserId(val value: UUID) : java.io.Serializable {
    init {
        // validate here
    }
    companion object {
        fun random() : YapilyReferenceUserId {
            return YapilyReferenceUserId(UUID.randomUUID())
        }
        @JsonCreator
        fun fromString(value: String): YapilyReferenceUserId = YapilyReferenceUserId(UUID.fromString(value))
    }

    @JsonValue
    fun asString(): String = value.toString()
}

/**
 * Unfortunately no detailed description exists in Yapily docs (https://docs.yapily.com/api/#tocS_PaymentAuthorisationRequestResponse)
 * I am guessing this may be a consent identifier issued by an institution (which would be very important for us.
 */
data class YapilyInstitutionConsentId(val value: String): java.io.Serializable {
    init {
        // validate here
    }
}

data class YapilyAccountIdentificationSortCode(val sortCode: String)
    : YapilyAccountIdentification {
    init {
        if (sortCode.length != 6) throw java.lang.IllegalArgumentException("Invalid sort code length ${sortCode.length}. It must be 6")
        try {
            sortCode.toInt()
        } catch (ex: java.lang.NumberFormatException) {
            throw java.lang.IllegalArgumentException("Invalid sort code format. It must be 6 digits long number")
        }
    }

    companion object {
        fun forTest() : YapilyAccountIdentificationSortCode {
            return YapilyAccountIdentificationSortCode("123456")
        }
    }

    override fun toYapily(): AccountIdentification {
        var result = AccountIdentification()
        result.type = AccountIdentification.TypeEnum.SORT_CODE
        result.identification = this.sortCode;
        return result;
    }

    override fun toDbString(): String {
        return "${AccountIdentification.TypeEnum.SORT_CODE}:$sortCode"
    }
}
data class YapilyAccountIdentificationAccountNumber(val accountNumber: String)
    : YapilyAccountIdentification {
    init {
        if (accountNumber.length != 8) throw java.lang.IllegalArgumentException("Invalid account number length ${accountNumber.length}. It must be 8")
        try {
            accountNumber.toInt()
        } catch (ex: java.lang.NumberFormatException) {
            throw java.lang.IllegalArgumentException("Invalid account number format. It must be 8 digits long number")
        }
    }

    companion object {
        fun forTest() : YapilyAccountIdentificationAccountNumber {
            return YapilyAccountIdentificationAccountNumber("12345678");
        }
    }

    override fun toYapily(): AccountIdentification {
        var result = AccountIdentification()
        result.type = AccountIdentification.TypeEnum.ACCOUNT_NUMBER
        result.identification = this.accountNumber;
        return result;
    }

    override fun toDbString(): String {
        return "${AccountIdentification.TypeEnum.ACCOUNT_NUMBER}:$accountNumber"
    }
}

/**
 * https://docs.yapily.com/guides/payments/payment-execution/#account-identifications-combinations
 */
class AccountIdentificationFactory {

    companion object {
        fun sortCode(value: String) : YapilyAccountIdentificationSortCode {
            return YapilyAccountIdentificationSortCode(value)
        }
        fun accountNumber(value: String) : YapilyAccountIdentificationAccountNumber {
            return YapilyAccountIdentificationAccountNumber(value)
        }
        fun fromDbString(dbString: String) : YapilyAccountIdentification {
            // TODO: handle edge cases. test
            val split = dbString.split(":")
            var type = AccountIdentification.TypeEnum.fromValue(split[0])
            var value = split[1]
            return when (type) {
                AccountIdentification.TypeEnum.SORT_CODE -> YapilyAccountIdentificationSortCode(value)
                AccountIdentification.TypeEnum.ACCOUNT_NUMBER -> YapilyAccountIdentificationAccountNumber(value)
                else -> throw java.lang.IllegalArgumentException("Unsupported AccountIdentification type ${type}")
            }
        }
    }
}